### ISSUE TITLE
Recursive references in openapi schema crashes the validator

### ISSUE THREAD

**Issue by sunspikes** [thephpleague/openapi-psr7-validator#11]
This part of the schema copied from my API which causes the schema resolution go in infinite loop and eventually crash the application

```
openapi: 3.0.0
info:
  title: 'API'
  version: '1.0'
servers:
  -
    url: 'https://localhost/v1'
    description: Dev
paths:
  /userGroup/:
    get:
      tags:
        - user
      summary: 'Get all user groups'
      operationId: userGroupGetCollection
      parameters:
        -
          name: limit
          in: query
          description: 'Limit the number of entries in the collection (default=10)'
          required: false
          schema:
            type: integer
            format: int32
        -
          name: offset
          in: query
          description: 'Retrieve entries of the collection at this offset (default=0)'
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'user group collection response'
          content:
            application/json:
              schema:
                allOf:
                  - { $ref: '#/components/schemas/Collection' }
                  - { properties: { entries: { type: array, items: { $ref: '#/components/schemas/UserGroup' } } }, type: object }
                  - { properties: { _embedded: { properties: { '/user/{userId}': { $ref: '#/components/schemas/User' } }, type: object } }, type: object }
components:
  schemas:
    Collection:
      required:
        - limit
        - count
        - offset
        - entries
      properties:
        limit:
          type: integer
          minimum: 0
        count:
          type: integer
          minimum: 0
        offset:
          type: integer
          minimum: 0
        entries: {  }
        _embedded: {  }
      type: object
      additionalProperties: false
    User:
      title: 'User model'
      required:
        - id
      properties:
        _embedded:
          properties:
            '/userGroup/{userGroupId}':
              $ref: '#/components/schemas/UserGroup'
            '/user/{userId}':
              $ref: '#/components/schemas/User'
          type: object
        id:
          type: integer
          minimum: 1
      type: object
      additionalProperties: false
    UserGroup:
      title: 'User group model'
      required:
        - id
        - name
      properties:
        _embedded:
          properties:
            '/user/{userId}':
              $ref: '#/components/schemas/User'
          type: object
        id:
          type: integer
          minimum: 1
        name:
          type: string
          minLength: 1
          nullable: true
      type: object
      additionalProperties: false
```

Here the the `User` and `UserGroup` models have cross references and this causes the schema resolver to go in indefinite recursion.

A solution to this would be: https://github.com/thephpleague/openapi-psr7-validator/pull/5

**Comment by scaytrase** [comment]
Well if we are talking about dealing recursion, than this is something what need to be dealt within @cebe Reader, I think. Because if we have recursion and multi-file at the same time than we will not resolve them any way. Looks like we need to implement some kind of resource tracking while resolving references

**Comment by scaytrase** [comment]
in case your `SAME_OPENAPI_FILE` has two references:
1. `SAME_OPENAPI_FILE`
2. `REMOTE_OPENAPI_FILE`

calling `resolveReferences` will fall into recursion
not calling `resolveReferences` will prevent `REMOTE_OPENAPI_FILE` resource from loading which cause failures later.

So proper solution IMO would be prevent infinte recursion, not disable reference resolution

**Comment by sunspikes** [comment]
@scaytrase Yes, exactly, that's what i meant above `resolveReferences` is needed only if there are remote references and yes the proper solution would be to prevent the infinite recursion.

**Comment by sunspikes** [comment]
I think it should be a pretty simple check

https://swagger.io/docs/specification/using-ref/#syntax

So any reference other than one starting with `#` will be a remote or URL reference. If in the document any reference is not starting with `#` we need to call `resolveReferences` afaics

**Comment by scaytrase** [comment]
But this does not solve the problem if file has both types of references.

I suggest to go from the other end and try to think whether we can patch this function https://github.com/cebe/php-openapi/blob/13b91759f9daccd90729e1c246bab791f13e59c8/src/SpecBaseObject.php#L343-L360

in order to not no fall into infinite recursion. At the first look we can keep a map of `resolvedReferences` within `ReferenceContext` instance and do not resolve references which we've resolved (or started resolving) once, just replcing them with already resolved objects from map

**Comment by sunspikes** [comment]
Yes, thanks. I think it better fixed in the reader. I can anyway work around by doing,

```
            $this->validatorBuilder = new ValidatorBuilder();
            $this->validatorBuilder->fromSchema(Reader::readFromYamlFile($schemaFile));
```
