### ISSUE TITLE
Strict validation of parameters

### ISSUE THREAD

**Issue by elnurvl** [thephpleague/openapi-psr7-validator#124]
Currently, requests having headers, body and query parameters outside the API specification pass the validation. Because of that, it is possible to make typos in the name of some optional parameters and still miss them during the tests. For example, if the `expires_in` body parameter is not a required parameter, then it is possible to accidentally set it as `expire_in` in the PHP code without breaking the tests because in that case the `expire_in` will be seen as a new parameter and the `expires_in` parameter will be assumed to be missing. Is it possible to strictly validate the parameters and headers against the API specification?

**Comment by scaytrase** [comment]
Yup, this library is about interpreting the spec and comparing request\responses with it. So whatever is not supported by the spec itself - not supported by the lib. If you find any part of spec which is not supported here - point us to the docs and we will be glad to implement it.

**Comment by elnurvl** [comment]
I appreciate following the official specification to be fully compatible. But would not it be convenient if it was possible to configure some options, as well as this one from the builder? I do not see why it would break the compatibility with the spec. You can see the [cdimascio/express-openapi-validator](https://github.com/cdimascio/express-openapi-validator) library as an example that allows such kind of tweaking.

**Comment by elnurvl** [comment]
Then what would be the recommended approach to validate optional request parameters with this tool? The only use case of this library for us is to test our codebase against the defined Open API and get a test failure when there are inconsistencies between the API description and the implementation. Respectfully, I do not see why it is more important to comply with the specification than validating against it while the main motivation behind the development of this package is the latter one.

**Comment by scaytrase** [comment]
Sorry for late response. I'd rather suggest to invest into extensibility of validator and allow userland implementations of validator (if not allowed so), so you can extend and implement your own validations bases on `x-` proerties. WDYT ?

**Comment by momala454** [comment]
As far as I understand, adding support for `unevaluatedProperties` should work.
Could you support this on this lib ?

**Comment by momala454** [comment]
As far as I understand, adding support for unevaluatedProperties should work.
Could you support this on this lib @scaytrase

**Comment by scaytrase** [comment]
@momala454 hello, since we bring OAS 3.1 with @DEVizzent 's fork of cebe/openapi - I think this would be possible if it's supported in the fork. If it is - feel free to open PR. as for me - I don't really have spare time to invest in developing this lib, but I'll be happy to review and accept a contribution.

Closing this for now, as the initial question was answered

**Comment by DEVizzent** [comment]
Did you try to set  'additionalProperties'  to false Inthe object schema? This make invalid al objects with properties not defined. @momala454 @elnurvl

**Comment by scaytrase** [comment]
@DEVizzent you can set `additionalProperties` for the parameter itself, for sure. But the question is how to prohibit unknown parameters themselves.

parameters a described (according to doc) like

```yaml
     parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
```

there is no place to say "I do not respect any unknown parameters, go away mr. Bad Request"
