### ISSUE TITLE
Usage of ServerRequestInterface#getQueryParams() may be unreliable

### ISSUE THREAD

**Issue by someniatko** [thephpleague/openapi-psr7-validator#128]
Based on discussion https://github.com/Nyholm/psr7/issues/181 (it's better to read it to get better context).

When validating URI query parameters against the OpenAPI request schema, this library relies on `ServerRequestInterface`'s `getQueryParams()` method https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/PSR7/Validators/QueryArgumentsValidator.php#L71-L72

However, it turned out that its behavior is inconsistent across the PSR7 / PSR17 implementations. For instance, it works as expected by the library if using `slim/psr7` implementation, however if using `nyholm/psr7` one, it would most probably return just an empty array — the current behavior of the lib requires setting those query params to the request manually via `withQueryParams()`.

This means the `ServerRequestInterface` created by `nyholm/psr7`'s factory will fail the OpenAPI validation if there are required query parameters in the schema.

I suggest that until it's fully clarified in the PSR, the lib should not rely on getQueryParams(), but parse URI instead.

**Comment by someniatko** [comment]
A quick update: I've just tested it using `nyholm/psr7-server` - if using their `ServerRequestCreator#fromGlobals()` with real requests to the PHP, the `getQueryParams()` works as expected. So probably it wasn't worth it creating this issue. I discovered this behavior during unit-testing of my app, so this behavior might be not so relevant to day-to-day usage.

**Comment by someniatko** [comment]
Looking at the unit tests of this lib, I see that it actually doesn't expect at all that query parameters will be parsed based on URI. Instead, they are manually set via `withQueryParams()`: https://github.com/thephpleague/openapi-psr7-validator/blob/master/tests/PSR7/QueryArgumentsTest.php

So it looks like there is no problem at all.

I'll leave this issue opened though and up to maintainers to close or leave opened, because probably you may have some thoughts on this.

**Comment by scaytrase** [comment]
Thanks @someniatko for your investigations! PSR implementations are sometimes not consistent indeed, that's true. But for now I see no problem with it, so I'll close it for now. Feel free to open new one or reopen this one if we face inconsistency problems in real cases
