### ISSUE TITLE
Multipart encoding validation only checks against a single content type

### ISSUE THREAD

**Issue by jimcottrell** [thephpleague/openapi-psr7-validator#134]
According to the OpenAPI spec for the `Encoding` object's `contentType` field (this also exists in a comment in `MultipartValidator::detectEncondingContentType()`:

> The value can be a specific media type (e.g. `application/json`), a wildcard media type (e.g. `image/*`), **or a comma-separated list of the two types**

The multipart validation as it currently exists only validates against `contentType` as a single entry, failing if `contentType` is defined as a comma-separated list.

I'll submit a PR for this.

**Comment by dwilmer-karify** [comment]
I recently ran into this issue as well. I see that there is a pull request ready, but I'm unfamiliar with the process. What would be the next step towards getting it accepted?
