### ISSUE TITLE
Path parameter with "/my-path/:parameter" format not recognized

### ISSUE THREAD

**Issue by sserot** [thephpleague/openapi-psr7-validator#138]
Hi,

In my code I implemented

```
$validator = (new \League\OpenAPIValidation\PSR7\ValidatorBuilder)->fromYamlFile($yamlFile)->getRequestValidator();

$match = $validator->validate($request);
```

In my OpenApi definition I have the parameters configured with `:my-parameter` in the path, it's Postman friendly https://learning.postman.com/docs/sending-requests/requests/#sending-parameters

```
    /context/entity/:id:
        get:
            $ref: 'my-yaml.yaml'
```

But the path parameters are only recognized with `/my-path/{parameter}` in the `League\OpenAPIValidation\PSR7\PathFinder::searchForCandidates` method

Is it possible to support this second format ?

**Comment by scaytrase** [comment]
Hello, is your schema valid OpenAPI schema? You can check this here https://editor.swagger.io/ if it's parsed correctly

**Comment by sserot** [comment]
Hi,

No it isn't

I generate my api documentation with [redocly](https://github.com/Redocly/redoc) and there is no error...

I will change the path parameters syntax

Thank you for your help
