### ISSUE TITLE
Get the name of the invalid property

### ISSUE THREAD

**Issue by scaytrase** [thephpleague/openapi-psr7-validator#14]
See https://github.com/lezhnev74/openapi-psr7-validator/issues/50 for discussion and details

**Comment by coatesap** [comment]
I expect the use-case for this package for 90% of users is going to be validating request bodies against a schema. As such, the fact that their isn't a clearly defined approach to to finding out which property failed and why seems to be a massive oversight.

**Comment by canvural** [comment]
Is there any update on this? Like @coatesap mentioned, I expected giving useful error messages for failed field(s), would be one of the main features of this package.

**Comment by scaytrase** [comment]
Created #57 to address this

**Comment by canvural** [comment]
@scaytrase Thank you!

**Comment by scaytrase** [comment]
I'll check if something could be released and perform a release soon
