### ISSUE TITLE
Parameters of type number in query or path

### ISSUE THREAD

**Issue by Identity-labs** [thephpleague/openapi-psr7-validator#140]
Hi,

Parameters number in query or path is always invalid because path or query is string.
May be add improvement on it ?
Shame to have put in everything in string.

Thx :)

**Comment by scaytrase** [comment]
Hello, can you please provide some test cases? Because yes, in an HTTP world everything is a string, since there is no way to distinguish between number and a numeric string

**Comment by Identity-labs** [comment]
Hi, yes sorry here an exemple who don't work

`/**
 * @OA\GET (
 *     path="/api",
 *     tags={"api"},
 *     description="api",
 *     summary="Get a list",
 *     @OA\Parameter(name="int_array", in="query", required=true, description="Array of int", @OA\schema(type="array", @OA\Items(type="integer"))),
 *     @OA\Parameter(name="number_array", in="query", required=true, description="Array of number", @OA\schema(type="array", @OA\Items(type="number"))),
 *     @OA\Parameter(name="string_array", in="query", required=true, description="Array of string", @OA\schema(type="array", @OA\Items(type="string"))),
 * )
 */
`

Parameters int_array & number_arrray don't work
Can be valided easyly with

`strval(intval($value)) == $value`
`strval(floatval($value)) == $value`

Or with regex ?

Thx

**Comment by scaytrase** [comment]
Can you provide an example of request?

Does it work without arrays? OAS 3 uses `form without explode` as [default serialization method](https://swagger.io/docs/specification/serialization/) for query argument. But this method is not really supported by PHP ( `/users?id=3&id=4&id=5` will register only `id=5` as value).

**Comment by Identity-labs** [comment]
Hi, 
No request is /users?id[]=3&id[]=4&id[]=5
You can make array or nested array in querystring.

**Comment by ijscoman1337** [comment]
Hey IdentityLabs, besides the question for scaytrase whether or not this is supposed to be part of his package...

I'm pretty sure you will be able to tackle your problem with pre-validation sanatization. For example you can
A good package for sanatizing data could be: https://github.com/elegantweb/sanitizer.

**Comment by Identity-labs** [comment]
So your lib dosen't valid all cases of openapi, it's not logique to implement another system to cast data. 
You can edit your readme with known issues to avoid people loosing time on it.

**Comment by scaytrase** [comment]
@Identity-labs the issue exists indeed, but I've not closed your issue as won't fix yet. I'm a bit busy last dasy to introduce a fix. I think that we have this feature here

https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/PSR7/Validators/SerializedParameter.php#L132-L137
called from here
https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/PSR7/Validators/ArrayValidator.php#L57
called from here
https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/PSR7/Validators/QueryArgumentsValidator.php#L58

But maybe something goes wrong.

If you want to help speed up thing you can bring a test case like here https://github.com/thephpleague/openapi-psr7-validator/tree/master/tests/FromCommunity to help me identify a problem

**Comment by Identity-labs** [comment]
It's fixed with the PR above :)
