### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by jokaorgua** [thephpleague/openapi-psr7-validator#151]
Would be nice to have Symfony 6 support. Do you plan to support it?

Currently, it is impossible to install the package on Symfony 6 because of cebe/php-openapi package which depends on Symfony-yaml prior to v6

**Comment by scaytrase** [comment]
I see you've already opened issue for `cebe/php-openapi`. There is nothing to do with symfony here. we depend on it only for `dev` purposes

**Comment by cebe** [comment]
php-openapi 1.6.0 now supports symfony 6
