### ISSUE TITLE
Need help: how to get detailed data about failed validation?

### ISSUE THREAD

**Issue by jokaorgua** [thephpleague/openapi-psr7-validator#153]
Hello. Could anyone recommend or explain how to extract detailed validation errors? Which field, error type, etc?

Thanks. 

I'm using such a code in symfony event listener
```php
$validator = (new \League\OpenAPIValidation\PSR7\ValidatorBuilder)->fromYamlFile($openapiFilePath)
                          ->getRequestValidator();
$validator->validate($psrRequest);
```

p.s. I've looked through the code and I do not see any public method to get such an info

**Comment by davidyell** [comment]
👍 
This would sure be a handy thing to have

**Comment by scaytrase** [comment]
Validation failure is expose through exception tree, it's [documented](https://github.com/thephpleague/openapi-psr7-validator#exceptions) in the readme. Basic exceptions are `ValidationFailed` for common PSR-7 validator process. You can inspect exception chain to get exact reason.
Some of the exceptions have programmatically accessible data, like breadcrumbs https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/Schema/Exception/SchemaMismatch.php#L13

**Comment by davidyell** [comment]
How does this `\League\OpenAPIValidation\PSR7\Exception\Validation\InvalidBody` tell me where to look in my json body?

**Comment by davidyell** [comment]
Apologies, but yes, dumping the whole exception it does indeed include way more helpful information! 🎉

**Comment by canvural** [comment]
@jokaorgua I'm using this code. I don't know your use case, but probably you can adjust it to your needs

```php
private function getValidationMessage(ValidationFailed $exception): string
    {
        $ex = $exception->getPrevious();

        if ($ex === null) {
            return $exception->getMessage();
        }

        if ($ex instanceof SchemaMismatch) {
            if ($ex->dataBreadCrumb() === null) {
                return $exception->getMessage();
            }

            $field = implode('.', $ex->dataBreadCrumb()->buildChain());

            return sprintf(
                'Validation against spec failed for "%s": "%s"',
                $field,
                str_replace(['Keyword validation failed: '], '', $ex->getMessage())
            );
        }

        return $exception->getMessage();
    }
```

**Comment by jokaorgua** [comment]
@scaytrase thanks. But as for me, the interface should be created for getting errors normally without hacks

@canvural thanks!

**Comment by scaytrase** [comment]
Interpreting validation errors is pure userland responsibility. Every project can have it's own implementation and it's own usecase (some use psr-7 validator, some validate raw data, etc). And there is nothing hacky in using fields [exampled in the readme](https://github.com/thephpleague/openapi-psr7-validator#standalone-openapi-validator) (yeah, maybe not that explicitly but anyway)
