### ISSUE TITLE
`$schema->nullable` can be `null` as of cebe/php-openapi 1.6

### ISSUE THREAD

**Issue by canvural** [thephpleague/openapi-psr7-validator#154]
Hello,

I just updated to `cebe/php-openapi` 1.6.0 and got an error in my test suite.

As of 1.6.0, `$schema->nullable` can be `null` : https://github.com/cebe/php-openapi/blob/master/src/spec/Schema.php#L130

This causes error here: https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/Schema/SchemaValidator.php#L60 `Argument #2 ($nullable) must be of type bool, null given`

Currently I don't have time send a PR with a fix. So just reporting it.

**Comment by cebe** [comment]
Linking related discussions for reference:

- https://github.com/thephpleague/openapi-psr7-validator/issues/118
- https://github.com/thephpleague/openapi-psr7-validator/issues/146

**Comment by scaytrase** [comment]
Implemented quick fix
