### ISSUE TITLE
Break with openapi 1.6.0

### ISSUE THREAD

**Issue by Identity-labs** [thephpleague/openapi-psr7-validator#157]
Hello, with our automated tests we have some error with last update of openapi

Openapi : cebe/php-openapi 1.6.0
Environnement : PHP 7.4

TypeError: Argument 2 passed to League\OpenAPIValidation\Schema\Keywords\Nullable::validate() must be of the type bool, null given, called in /home/gitlab-runner/builds/1AgP1Uo1/0/vendor/league/openapi-psr7-validator/src/Schema/SchemaValidator.php

Thx

**Comment by scaytrase** [comment]
Already fixed in 0.17 https://github.com/thephpleague/openapi-psr7-validator/pull/155/files#diff-c1f4a8b300cd7d0395ecc749ae31db63cccfc8c284e269941ea807454416f8f3R60
