### ISSUE TITLE
Make compatible with PHP8

### ISSUE THREAD

**Issue by PatchRanger** [thephpleague/openapi-psr7-validator#199]
`openapi-psr7-validator` latest version `0.21` https://github.com/thephpleague/openapi-psr7-validator/blob/0.21/composer.json depends on `riverline/multipart-parser: ^2.0.3` .

`riverline/multipartparser` up to version `2.1.0` depends on `laminas/laminas-diactoros: 1.8.7` https://github.com/Riverline/multipart-parser/blob/2.1.0/composer.json

And `laminas/laminas-diactoros: 1.8.7` is the latest version in 1.x - but it does not support php 8.0.

Therefore, in order to make `openapi-psr7-validator` compatible with PHP 8 we need to upgrade `riverline/multipartparser` to version `2.1.1`.

I am going to provide a PR soon.

**Comment by scaytrase** [comment]
project is already compatible with PHP8, we have tests for it

https://github.com/thephpleague/openapi-psr7-validator/actions/runs/4601634239/jobs/8129719057
https://github.com/thephpleague/openapi-psr7-validator/actions/runs/4601634239/jobs/8129718692

`laminas/laminas-diactoros` is a `dev` requirement for `riverline/multipart-parser`, so it gives nothing for real dependency tree
