### ISSUE TITLE
Regular expresions in path

### ISSUE THREAD

**Issue by imefisto** [thephpleague/openapi-psr7-validator#22]
Hi guys,

Do we have a way to describe an endpoint with paths with a variable number of segments? For example, I have a route declared with this:

`'/open/{fullpath:.*}'`

This let me to process routes like:

/open/some-file.ext
/open/some-folder/some-file.ext
/open/some-folder/some-folder2/some-file.ext
etc

While I don't have problems with the code, the validator doesn't allow this:

"OpenAPI spec contains no such operation [/open/some-folder/some-file.ext,get]"

Digging in the spec, I found this comment where a "/seg1/seg2/*" is mentioned:

https://github.com/OAI/OpenAPI-Specification/issues/892#issuecomment-281692262

Regards.

**Comment by scaytrase** [comment]
Looks like it's not supported by the spec itself?

**Comment by scaytrase** [comment]
I think we cannot validate things that are not in spec at the moment, as this will create our own flavour of spec, which would confuse other users. Feel free to reopen this issues when the OAS will have this feature
