### ISSUE TITLE
Support PSR-16 cache

### ISSUE THREAD

**Issue by PatrickG** [thephpleague/openapi-psr7-validator#23]
I think it would be nice if this lib would support not only PSR-6 but also PSR-16 caches.
I'm willing to provide a pull request for this feature.

**Comment by scaytrase** [comment]
Actually any PSR-16 cache could be converted into PSR-6 cache using things like this. https://github.com/symfony/cache/blob/master/Adapter/Psr16Adapter.php

I'm not sure that every lib should carry it's own adapter instead of reusing existing ones from other libs

**Comment by PatrickG** [comment]
You don't need a complex adapter to support both interfaces.

Then, this lib maybe should support the most widely used interface, because there are bridges from PSR-16 to PSR-6 as well, and this lib does not use any of the more complex features of PSR-6 anyway.

**Comment by scaytrase** [comment]
Since there is no advance on this idea, I'll close this as won't fix, but I'll always consider a PR with improvements as a base for future cache mechanics improvements

**Comment by osteel** [comment]
In case someone winds up on this thread like I did, here's an [example implementation](https://github.com/osteel/openapi-httpfoundation-testing/pull/33/commits/29f1e5367e24b7f38f88bdd6777cfdb3e3782f89#diff-1954d0325447a788498d550372ab58597a2ac8a18502ed87602c644ac96c5f64) of a PSR-16 to PSR-6 conversion
