### ISSUE TITLE
Upcoming changes to reference resolving

### ISSUE THREAD

**Issue by cebe** [thephpleague/openapi-psr7-validator#28]
Hi all,

just wanted to let you know about the changes I made to reference resolving.

We had this issue popping up before, where references are only partially resolved. These should be fixed by https://github.com/cebe/php-openapi/pull/39 which will be in version 1.3 (will be released tomorrow if all works well).

So if you bump the required version in composer.json to 1.3, calling `Reader::readFromYamlFile()` will automaticall resolve all references in the context of the file (absolute Path or URL required) and calling `resolveReferences()` manually is not necessary anymore.

**Comment by scaytrase** [comment]
Fixed in #29 great work, @cebe and @sunspikes !
