### ISSUE TITLE
Validation of callbacks

### ISSUE THREAD

**Issue by lezhnev74** [thephpleague/openapi-psr7-validator#3]
Some way to validate the request and response of callbacks would be great.

I think the validation per se would work, but there needs to be some other way to resolve the specs. Right now, the specs are loaded based on a passed OperationAddress which doesn't fit for callbacks.

### Adding more docs:

https://swagger.io/docs/specification/callbacks/
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#callback-object

**Comment by digilist** [comment]
Please consider also for more discussion and ideas https://github.com/lezhnev74/openapi-psr7-validator/issues/52
