### ISSUE TITLE
Exception InvalidBody will not thrown (at 0.3.3/0.4.0)

### ISSUE THREAD

**Issue by Nobody1809** [thephpleague/openapi-psr7-validator#32]
Since version 0.3.3 and 0.4.0 the validator will not throw an InvalidBody Exception. 

Version 0.3.2 throws this validation exception.

**Comment by scaytrase** [comment]
Could you please provide more details on which schema and data you are trying to validate?

**Comment by Nobody1809** [comment]
I can give you just some code snippets:

schema.yaml:
`components:
  schemas:
    prescription:
      properties:
        exampleTyp:
          type: string
          enum:
            - VALID
            - STILLVALID`

using functions:
ValidatorBuilder -> fromYamlFile and ServerRequestValidator -> validate

until test data:
`$data = [
            'exampleTyp' => 'INVALID',
        ];

$this->expectException(InvalidBody::class);`

Output: (for version 0.3.3 and 0.4.0) 
Failed asserting that exception of type "OpenAPIValidation\PSR7\Exception\Validation\InvalidBody" is thrown.

**Comment by scaytrase** [comment]
Components are just re-usable parts of schema,actually there is no schema defined in your sample. Consider re-check your actual schema/

We already have the test for case you are talking about

https://github.com/thephpleague/openapi-psr7-validator/blob/5d2a74ed7b94511c89b5c79a00835b72844fd012/tests/Schema/Keywords/EnumTest.php#L30-L48

**Comment by Nobody1809** [comment]
I wrote a short example test for you. Please try this yaml schema and the used methods.

```php
public function testValidateFromYamlContentWithInvalideBody(): void
    {
        $filePath = __DIR__.'/../fixtures/schema.yaml';
        $contentYaml = file_get_contents($filePath);

        $url = '/api/test/create';
        $headers = new Headers();
        $headers->addHeaders(['Content-Type' => 'application/json']);

        $data = [
            'exampleTyp' => 'INVALID',
        ];

        $request = (new Request())->setMethod(Request::METHOD_POST)
                                      ->setUri($url)
                                      ->setHeaders($headers)
                                      ->setContent(json_encode($data))
                                      ->setPost(new Parameters([]));

        $serverRequest = Psr7ServerRequest::fromZend($request);

        $serverRequestValidator = (new ValidatorBuilder())->fromYaml($contentYaml)->getServerRequestValidator();
        $this->expectException(InvalidBody::class);
        $serverRequestValidator->validate($serverRequest);
    }
```
```yaml
openapi: 3.0.0
paths:
  /api/test/create:
    post:
      description: 'Test'
      operationId: api.prescription.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/prescription'
      responses:
        '200':
          description: 'ok'
components:
  schemas:
    prescription:
      properties:
        exampleTyp:
          type: string
          enum:
            - VALID
            - STILLVALID
```

**Comment by scaytrase** [comment]
Yea, now looks valid. , I've rewrote the test to match ours in #34 .

@cebe, looks like there is no default `type=object` for components schema now. Explicitly adding `prescription.type: object` makes the test pass, but I think type is object by default for schema with properties, isn't ?

**Comment by cebe** [comment]
> @cebe, looks like there is no default `type=object` for components schema now. Explicitly adding `prescription.type: object` makes the test pass, but I think type is object by default for schema with properties, isn't ?

I could not find anything about a default value of `type` in OpenAPI 3.0.2, also not in the JSON schema specifications.

The only thing that comes close is 

> An empty schema is a JSON Schema with no properties, or only unknown properties.
> https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.4

But this seems to be more about the type of the schema itself instead of the type of validated data.

> https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-4.2
>  Validation keywords that are missing never restrict validation.  In
   some cases, this no-op behavior is identical to a keyword that exists
   with certain values, and these values are noted where known.

following this part, a missing "type" should mean that the validated data can be of any type, it does not restrict validation. Assuming a default value of `object` would be wrong as far as I see.

**Comment by cebe** [comment]
So for the current issue you should validate all properties if the input data is an object, but not validate the type of the input data. Also, ignore properties if the input data is not an object:

> https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-4.1
> Most validation keywords only limit the range of values within a
   certain primitive type.  When the primitive type of the instance is
   not of the type targeted by the keyword, the validation succeeds.

**Comment by scaytrase** [comment]
@cebe So you'd better consider this as won't fix?

**Comment by cebe** [comment]
nope, the current schema does not restrict the type of input data, so validation has to check the type of input data to decide how to proceed with the validation. If the input data is an object, you must validate the properties, but if the input data is not an object, the validation does not fail.

**Comment by scaytrase** [comment]
Hm, I've got your point. So we should infer data type if schema does not restrict it.
