### ISSUE TITLE
Beginner mistakes, 

### ISSUE THREAD

**Issue by StephanKrauss** [thephpleague/openapi-psr7-validator#37]
Hello, I'm testing the league / openapi-psr7-validator. Unfortunately I have a problem.
I originally use the Swagger Yaml file from https://editor.swagger.io.

My script:
```
$yamlFile = "path/to/my/petshop_swagger.yaml";
$yamlFileContent = file_get_contents($yamlFile);

$validator = (new \League\OpenAPIValidation\PSR7\ValidatorBuilder)->fromYamlFile($yamlFile)->getServerRequestValidator();
```

I get the error message:
```
Fatal error: Uncaught Error: Call to a member function setReferenceContext() on array in C:\xampp1\htdocs\swagger-php\vendor\cebe\php-openapi\src\spec\Reference.php on line 177
```

What is wrong ?

Your sincerly Stephan

**Comment by scaytrase** [comment]
Hello, Stephan. Is it the whole stack trace you got alongside with the error?

**Comment by scaytrase** [comment]
@cebe it seems like `evaluate` method could return an array instead of `SpecObjectInterface` expected here https://github.com/cebe/php-openapi/blob/7403ab2f739bca7185966f66a0f3d2d444d3adc7/src/spec/Reference.php#L177

**Comment by scaytrase** [comment]
Yep, indeed, creating schema from petstore yaml fails

**Comment by scaytrase** [comment]
To reproduce

```php
(new ValidatorBuilder())->fromJson(file_get_contents('https://petstore.swagger.io/v2/swagger.json'))->getServerRequestValidator();
```

**Comment by scaytrase** [comment]
Hmm, loooks like that `fromJson` and `fromYaml` still did manual reference resolution. And changes in cebe/php-openapi have a BC-break somewhere. A line above works with 1.2.1 and fails with ^1.3.0 (1.3.0, 1.3.1)

**Comment by cebe** [comment]
> `https://petstore.swagger.io/v2/swagger.json`

that is swagger/openapi version 2, which is not supported by cebe/php-openapi.

Anyway, there is an issue, not a BC break, but a bug introduced in 1.3.0, I assumed that a reference can only return a SpecBaseObject, but it seems it is also possible to reference some part of the json/yaml structure that has no representation of a spec specific object in which case I should check for the type before setting the context. thanks, @scaytrase, created an issue here: https://github.com/cebe/php-openapi/issues/47

**Comment by scaytrase** [comment]
> that is swagger/openapi version 2, which is not supported by cebe/php-openapi.

I think we should get an exception for unsupported schemas, what do you think about it?

**Comment by cebe** [comment]
yes, that would be helpful.

**Comment by cebe** [comment]
The bug is fixed in https://github.com/cebe/php-openapi/releases/tag/1.3.2

**Comment by scaytrase** [comment]
@StephanKrauss could you please verify, that problem is gone using updated dependencies?

**Comment by yun-cn** [comment]
I also get this error

**Comment by yun-cn** [comment]
Is there any good solution?

**Comment by scaytrase** [comment]
Have you tried updated dependencies?

**Comment by yun-cn** [comment]
Thanks, I fixed it .
