### ISSUE TITLE
simple example openapi-psr7-validator

### ISSUE THREAD

**Issue by StephanKrauss** [thephpleague/openapi-psr7-validator#38]
Hello,
i start to deal with the open
api-psr7-validator.

Is there any example for using the
openapi-psr7-validator ?

With friendly greetings

Stephan

**Comment by scaytrase** [comment]
Hi @StephanKrauss there is no real examples, but there are a lot of tests for different parts of PSR-7 validation where you can find specs and request for pass\fail cases

https://github.com/thephpleague/openapi-psr7-validator/tree/master/tests/PSR7

**Comment by StephanKrauss** [comment]
Hi, thanks for the reply. At the moment I am studying the following tutorial:

https://lessthan12ms.com/openapi-with-php-documenting-and-testing-api-automatically.html


Greeting Stephan

**Comment by StephanKrauss** [comment]
Ups, i get an error message.

Class 'OpenAPIValidation\PSR15\SlimAdapter' not found

is there an adapter for the slim framework ?

Your sincerly Stephan

**Comment by scaytrase** [comment]
This article is a bit outdated. Everything is moved to the `League` namespace, since package was adopted by the PHP League project. Please, check out the main repo readme https://github.com/thephpleague/openapi-psr7-validator/blob/master/README.md

**Comment by nicolascastel** [comment]
Hi, 
Thanks for your project.  I test it for testing my api automatically with openApi 3.0.
But I can not test my locally hosted API (localhost). 

My code :

`$request = new ServerRequest('get','http://localhost:8083/api/v1/stations/'); `
`$validator = (new ValidatorBuilder())->fromYamlFile($this->apiSpecFile)->getServerRequestValidator();`
`$validator->validate($request);
        $this->addToAssertionCount(1);`

 It always OK even if my server is down....

Have you a simple example to do this?

Thanks

**Comment by nicolascastel** [comment]
Hi,
It's OK. Juste use  Client :

```
$client = new GuzzleHttp\Client();
$res = $client->request('GET', "http://localhost:8083/api/v1/stations");
$addr    = new OperationAddress('/stations', 'get');
$this->responseValidator->validate($addr, $res);
```
Thanks for your library !

**Comment by scaytrase** [comment]
Yes, you should do an actual request to the server in order to validate the real response.

I'm closing this since no other questions raised. Feel free to open new issues if needed.
