### ISSUE TITLE
Spec Finder Not Always Finding

### ISSUE THREAD

**Issue by edmondscommerce** [thephpleague/openapi-psr7-validator#42]
I found that SpecFinder as it was trying to find paths based on pure string matching which doesnt work if the path contains paramters

this PR fixes that: https://github.com/thephpleague/openapi-psr7-validator/pull/40

**Comment by b-boehne** [comment]
Any chance his PR will get merged? All our tests fail because of "no such operation" errors if paths have a path parameter.

**Comment by scaytrase** [comment]
At this state - no. original author has abanoned his PR, but if you really need these changes - feel free to pick it up and finish

**Comment by scaytrase** [comment]
Should be fixed with https://github.com/thephpleague/openapi-psr7-validator/pull/76
