### ISSUE TITLE
allOf doesn't work with $ref

### ISSUE THREAD

**Issue by yunosh** [thephpleague/openapi-psr7-validator#51]
Whe using `allOf` to compose a reference with a single object, the object is ignored. Futhermore, writing a failing unit test for this issue isn't possible either, because the schema validator requires all `allOf` components to be a `cebe\openapi\spec\Schema` and doesn't allow `cebe\openapi\spec\Reference`.

**Comment by yunosh** [comment]
```
<?php

declare(strict_types=1);

namespace League\OpenAPIValidation\Tests\FromCommunity;

use League\OpenAPIValidation\Schema\Exception\TypeMismatch;
use League\OpenAPIValidation\Schema\SchemaValidator;
use League\OpenAPIValidation\Tests\Schema\SchemaValidatorTest;

final class AllOfTest extends SchemaValidatorTest
{
    public function testItValidatesAllOfGreen() : void
    {
        $spec = <<<SPEC
schema:
  allOf:
    - \$ref: '#/components/schemas/Base'
    - type: object
      properties:
        age:
          type: integer
components:
  schemas:
    Base:
      type: object
      properties:
        name:
          type: string
SPEC;

        $schema = $this->loadRawSchema($spec);
        $data   = ['name' => 'Dima', 'age' => 10];

        (new SchemaValidator())->validate($data, $schema);
        $this->addToAssertionCount(1);
    }

    public function testItValidatesAllOfRed() : void
    {
        $spec = <<<SPEC
schema:
  allOf:
    - \$ref: '#/components/schemas/Base'
    - type: object
      properties:
        age:
          type: integer
components:
  schemas:
    Base:
      type: object
      properties:
        name:
          type: string
SPEC;

        $schema = $this->loadRawSchema($spec);
        $data   = ['name' => 'Dima', 'age' => 10.5];

        $this->expectException(TypeMismatch::class);

        (new SchemaValidator())->validate($data, $schema);
    }
}
```

**Comment by scaytrase** [comment]
Failing test is also test, even if it fails by type error. I'll take a look on this, thanks for reporting

**Comment by rejinka** [comment]
Tried to fix this issue (and am doing so further). The problem exists for all *Of keywords, as the code indicates. A possible solution could be to extend League\OpenAPIValidation\Schema\Validator::validate(), so that it also allows references as second parameter and a possibility to resolve this reference to a schema.

**Comment by scaytrase** [comment]
I thought that all references are resolved on schema loading...

**Comment by rejinka** [comment]
They do, as i found out, a few minutes ago. By the factories, not by SchemaValidatorTest::loadRawSchema()

**Comment by rejinka** [comment]
#55 in combination with this tests show, that allOf does work with references. As @scaytrase indicated, the validator isn't responsible for resolving references to schemas. This is done before in the Factories. Then there aren't any references anymore, which the validator has to deal with.

**Comment by scaytrase** [comment]
I've merged tests fix, is this still a problem?

**Comment by rejinka** [comment]
I don't see a problem anymore. The issue in our project, which was the source for this issue, is already resolved.

**Comment by scaytrase** [comment]
Let me know if problem is still actual
