### ISSUE TITLE
InvalidQueryArgs::becauseValueDoesNotMatchSchema always expect query arguments to be a string

### ISSUE THREAD

**Issue by bolanle11** [thephpleague/openapi-psr7-validator#52]
The function `\League\OpenAPIValidation\PSR7\Exception\Validation\InvalidQueryArgs::becauseValueDoesNotMatchSchema(string $argumentName, string $argumentValue, OperationAddress $address, SchemaMismatch $prev)`  always expects `$argumentValue` to have  type `string` but that may not be the case for all query arguments, e.g. for the url `/api/fields[0]=id&fields[1]=name`, the query parameter will be type an `array`

**Comment by scaytrase** [comment]
Looks valid, thanks for reporting! Can you please provide a failing test case to speedup things?

**Comment by tschelhas** [comment]
I also have this issue. Can I help somehow to fix this ?

**Comment by scaytrase** [comment]
Sure, I didn't noticed that @bolanle11 created commit referencing this issue (there is no notificaiton about these things). I think you can try to fix exception signature to accept any data type and maybe somehow serialize it, or just omit the value itself in the message
