### ISSUE TITLE
Multipart form multiple file uploads

### ISSUE THREAD

**Issue by m50** [thephpleague/openapi-psr7-validator#62]
I seem to have run into an issue that seems to go against what I can find in online documentation.

According to the documentation on [swagger's website](https://swagger.io/docs/specification/describing-request-body/file-upload/) on multiple file uploads, you need to specify a parameter as an array of binary strings.

However, this package says that is incorrect.

Instead, I get `Body does not match schema for content-type \"multipart\/form-data\" for Request [put \/clam\/scan]`:

![image](https://user-images.githubusercontent.com/3577147/82738828-516ed400-9d00-11ea-831a-3c8916d0ad68.png)

However, if I set it to a singular binary string (not an array), it works with no issue:

![image](https://user-images.githubusercontent.com/3577147/82738856-78c5a100-9d00-11ea-906a-6435df0ba505.png)

I used exactly the same syntax that is provided in that documentation, except with the name "upload" instead of filename.

I'm not sure if swagger is wrong here, or if this validator is, but one of them is incorrect.

For my project, it's not a big deal, but something worth mentioning.

**Comment by scaytrase** [comment]
Can you please share an example curl comand (both success and failing) and sample schema to check it againts? I can't get difference with your screenshots in the term of request changes

**Comment by m50** [comment]
The request is the exact same in both cases, the only difference is the Spec.

Version that doesn't work:

```yaml
  /clam/scan:
    put:
      summary: Request a scan from clamav
      tags:
        - ClamAV
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AV-upload-response'
              examples:
                Example:
                  value:
                    id: 86135476-7d77-47f2-bd42-851b24e42570
                    code: 202
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error-Response'
              examples:
                Example:
                  value:
                    message: No Files provided.
                    code: 422
      operationId: clam-a-v.scan
      description: ...
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                upload:
                  type: array
                  items:
                    type: string
                    format: binary
          application/gzip:
            schema:
              type: string
              format: binary
          application/octet-stream:
            schema:
              type: string
              format: binary
        description: 'Pass a `.tar.gz` file to pass multiple files, or use multipart/form-data. Otherwise pass a singular file.'
```

but if I change the requestBody like so:

```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                upload:
                  type: string
                  format: binary
          application/gzip:
            schema:
              type: string
              format: binary
          application/octet-stream:
            schema:
              type: string
              format: binary
```

It works.

The request is exactly the same between the two, and the only difference is what is in the yaml.

Does that help clarify?

**Comment by scaytrase** [comment]
I've got that you are talking about, thanks. I'll check it 

What if you have an array spec and `upload[]` as the field name in your ui client instead of `upload`?

**Comment by m50** [comment]
I don't have an example right now, but had tried that, I got the same error, it made no difference.

I also tried `upload[0]` and `upload[1]` which didn't work either.

**Comment by scaytrase** [comment]
I've implemented a test with your schema and found a bug, thank you.

https://github.com/thephpleague/openapi-psr7-validator/blob/2091dd65ba388a2cdabc0f162e3864e6700f09f0/src/PSR7/Validators/BodyValidator/MultipartValidator.php#L236

This part does respect the case that files can be not just a flat array but a tree (it's stated in the docs for iterated method)
