### ISSUE TITLE
slim3 in subdirectory confuses Specfinder because of missing leading slash

### ISSUE THREAD

**Issue by lletourn** [thephpleague/openapi-psr7-validator#68]
When running slim3 in a subdirectory, the behaviour of getPath is to remove the leading slashas explained here:
https://github.com/slimphp/Slim/issues/1724

This causes issues with specfinder which tries to match a path with leading / with one without.
`Spec: v3/teams spec: #/v3/teams/?$#`

Also the openapi spec says leading slashes in paths is mandatory.

Not too sure how this should be solved.

**Comment by scaytrase** [comment]
Not sure that I've got the problem. Validator accepts requests with invalid paths? Could you please provide schema and request example?

**Comment by lletourn** [comment]
My project structure:
```
web/
      openapi/ <--- definition is here
      api/  <---slim is here
      webapp/ <--- stuff
```
openapi.json
```
  "paths": {
    "/v3/teams": {
        "get": {
            "tags": ["Teams"],
            "summary": "Get the list of all the teams",
            "description": "Get the list of all the teams",
            "operationId": "teamActions::getAll",
            "responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {"$ref": "#/components/schemas/Team"}
                            }
                        }
                    }
                }
            }
        }
    }
 },
  "servers": [
    {
      "url": "https://localhost:4443/api",
      "description": "Local server"
    },
```

This causes:
```
Type: League\\OpenAPIValidation\\PSR7\\Exception\\NoOperation
Message: OpenAPI spec contains no such operation [v3/teams,get]
File: /data/src/restapi/vendor/league/openapi-psr7-validator/src/PSR7/Exception/NoOperation.php
Line: 16
```

When going to https://localhost:4443/api/v3/teams

**Comment by lletourn** [comment]
only way I can make this work is to remove the leading slash in the path definition which is not standard and breaks many openapi tools.

**Comment by scaytrase** [comment]
I think you can try with replacing this middleware with your own, which also replaces the path in request object before validation (but keeping the original for later use)

https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/PSR15/ValidationMiddleware.php
