### ISSUE TITLE
validation exception - how to differentiate between request and response validation exceptions?

### ISSUE THREAD

**Issue by stefanoj3** [thephpleague/openapi-psr7-validator#69]
I was following the examples in the readme and I realized that the middleware might have a flaw: there is no way to differentiate between validation exception that are thrown when validating the request (where I would like to return a 400 to the caller) and validation exceptions happening when the middleware is validating the response (where I would like to return a 500, since there is nothing the caller could do to fix it from their side).

Here an example that illustrates what do I mean:
```php
$psr15Middleware = (new \League\OpenAPIValidation\PSR15\ValidationMiddlewareBuilder)->fromYamlFile($yamlFile)->getValidationMiddleware();

$stack-add($psr15Middleware)

try {
      $response = $stack->handle($request);
} catch (\League\OpenAPIValidation\PSR7\Exception\Validation\InvalidBody $e) {
     # is this failing because of the request? or the response ?
}
```

Of course I can solve this by defining my own middleware that depends on the validator, but I'm wondering if am I not using it as intended? or was this overlooked?

**Comment by scaytrase** [comment]
I'm not really using these middleware, so I'd better summon here @lezhnev74 to give some proper answers.

https://github.com/thephpleague/openapi-psr7-validator/blob/93e17cf2ab9c2b0601e14b628aeadc6a9b2e31b1/src/PSR15/ValidationMiddleware.php#L37-L43

As far as I can see there is two distinct processes for validation. So we can rethrow their exception with something like `RequestValidation` and  `ResponseValidationFailed` which both wraps respective exceptions as prev.

**Comment by lezhnev74** [comment]
Hey @stefanoj3 @scaytrase! I like @scaytrase's suggestion. As of now exceptions are not really dependent on the message type (request, server request, or response). So we can actually add two new exceptions just for the middleware case. Let me prepare a patch (should be straightforward).

**Comment by lezhnev74** [comment]
@scaytrase we can go in two ways:
- add new exceptions only for the middleware (this solution is backward compatible)
- a more foundational change will break current API
  - add 3 new exceptions in this namespace `League\OpenAPIValidation\PSR7\Exception\`: `InvalidRequestMessage`, `InvalidServerRequestMessage`, `InvalidResponseMessage`.
  - wrap any exception thrown in `ServerRequestValidator`, `RequestValidator`, `ResponseValidator` inside of the new ones.

what is your opinion?

**Comment by scaytrase** [comment]
Since we are still on 0.x versions breaking the API looks good for me with proper versioning. This way seems to me more useful in the future.

**Comment by stefanoj3** [comment]
If you guys agree that this change makes sense I'd be happy to submit a PR with the change.

**Comment by lezhnev74** [comment]
@stefanoj3 yesterday I did initial change in the code (see #70) but I did not have time to update the tests, which are now red. If you have time, you can catch up and work on the tests in that PR.
