### ISSUE TITLE
Optional response header

### ISSUE THREAD

**Issue by AdamLutka** [thephpleague/openapi-psr7-validator#73]
League\OpenAPIValidation\PSR7\Validators\HeadersValidator assumes that every header in response is required. But there is a field "required" in header specification https://github.com/OAI/OpenAPI-Specification/issues/321#issuecomment-284074270.

**Comment by scaytrase** [comment]
I've dig some history, looks valid. looks like this PR https://github.com/lezhnev74/openapi-psr7-validator/issues/30 added support only for request objects
