### ISSUE TITLE
Bad performance in the PathFinder

### ISSUE THREAD

**Issue by elythyr** [thephpleague/openapi-psr7-validator#79]
Hello,
First thanks for the great work you've done here.

I wanted to use this library to validate the requests/responses of our API within our codeception tests.
During my experimentation with this project I noticed a performance issue related to the `PathFinder` service.
I can't share my `swagger.yaml` but I did my tests with a 2MB file.

The issue is that searching a path is too long, this is because of the `PathFinder::findServersForOperation()` method.
More specifically the instruction `$this->openApiSpec->getSerializableData()` which takes in average 0.8s.

The method `PathFinder::search()` which trigger the previous calls is used in multiple places which result in an average time of 4s to validate both the request and the response.

Possible solution:
When investigating the issue I realized that this part seems unnecessary:
```php
        // 3. Check servers on root level
        if (array_key_exists('servers', (array) $this->openApiSpec->getSerializableData()) &&
            count($this->openApiSpec->servers) > 0) {
            return $this->openApiSpec->servers;
        }

        // fallback
        return [new Server(['url' => '/'])];
```

Indeed in the `OpenApi` class, the `servers` property is declared with a default value of `[new Server(['url' => '/'])]`, just as the fallback you used.
Therefore there is no need to test if the key actually exists neither as to ensure there is at least 1 server defined and this could simply be:
```php
        return $this->openApiSpec->servers;
```

I'm not familiar with the OAS3 specification nor as I am with the `cebe/php-openapi` library, so I didn't want to open a PR without discussing it here first.
I don't think my proposition will have any impact since the `SpecBaseObject::getSerializableData()` method does not affect the state of the object.

**Comment by scaytrase** [comment]
Good catch. @lezhnev74 can you explain why `getSerialzableData` is utilized there ? I have no idea of problems i helps to overcome instead of direct checking `$this->openApiSpec->servers` 

https://github.com/thephpleague/openapi-psr7-validator/commit/222e653b883c335f5d8a8c6ff5a97396144033fc#diff-27a2f3aebcedd16f8d12913d2f552120R121-R138

**Comment by lezhnev74** [comment]
Hey guys! If I remember that well, all the ifs were to prevent "no servers" case. However, this statement was probably overlooked:
```
An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of /.
```

The problem that `PathFinder::findServersForOperation` solves is locating the correct server config, which can be set at any level (operation, path or global api level). I believe `getSerialzableData` was used exactly for that purpose, to find the explicitly given server config (by inspecting if the key `servers` actually present). If I recall correctly, the code was meant to distinguish these two cases:
- server config was given explicitly in YAML file
- server config was not given so we fell back to the defaults

Performance is important, so I vote for rewriting this part for that purpose. Go ahead and write a new implementation for this part.

**Comment by scaytrase** [comment]
> the code was meant to distinguish these two cases:
Sounds reasonable. There is no way to get "raw" servers value for path item, as far as I can see. @cebe shouldn't defaults for servers be applied only for root openapi schema, but not for underlying objects? Is there a way to get raw servers property value from schema?

**Comment by cebe** [comment]
`getSerialzableData()` does return the JSON representatoin of the current object so you are not testing two different cases but checking the same data in two different ways.

There is no way to get the original data an object was built from.

The fallback to the default is unnecessary as far as I see because php-openapi already cares for returning the default if no server is specified:

https://github.com/cebe/php-openapi/blob/3d356d3e694d99434319057f2f9d35fad9ba3d9f/src/spec/OpenApi.php#L52-L58

**Comment by lezhnev74** [comment]
Ok, if there is no way to detect if `servers` is actually given by the user or fell back to default, it can be a pickle.

The usecase that was meant to be here:
- check if operation has servers set, if so - return
- if not, check path level, if servers set - return
- and, at last, fallback to global servers (which can default to anything if not set).

I am wondering if it is possible to implement the above?

**Comment by elythyr** [comment]
What about:
```php
    private function findServersForOperation(OperationAddress $opAddress) : array
    {
        $path      = $this->openApiSpec->paths->getPath($opAddress->path());
        $operation = $path->getOperations()[$opAddress->method()];

        // 1. Check servers on operation level
        if (isset($operation->servers) && count($operation->servers) > 0)) {
            return $operation->servers;
        }

        // 2. Check servers on path level
        if (isset($path->servers) && count($path->servers) > 0)) {
            return $path->servers;
        }

        return $this->openApiSpec->servers;
    }
```

The `operation` and `path` does not have a default value for the `servers` property so we still check the property exists with `isset` to avoid a serialization.
And we simply return the server of the root specification since it will never be empty anyway.

If that's up to you let me know if you want me to take care of the PR, I have the time and I would have to fork anyway because I can't use the package without a fix.

**Comment by lezhnev74** [comment]
> The operation and path does not have a default value for the servers

This simplifies everything. @elythyr do you want to write a test for this? Please open a new PR if you are willing to take care of it.

**Comment by scaytrase** [comment]
Unfortunatelly there is `_isset` implementation for SpecBaseObject

https://github.com/cebe/php-openapi/blob/3d356d3e694d99434319057f2f9d35fad9ba3d9f/src/SpecBaseObject.php#L353-L360

It will check the default values too, so servers are always set according to this logic

**Comment by elythyr** [comment]
There is no defaults sets for `operation` and `path` if I'm not mistaken.
For the `operation`: https://github.com/cebe/php-openapi/blob/3d356d3e694d99434319057f2f9d35fad9ba3d9f/src/spec/Operation.php#L54-L59
For the `path` the method is not even overrided.

> This simplifies everything. @elythyr do you want to write a test for this? Please open a new PR if you are willing to take care of it.

This is only refactoring, the existing test passing should be the only thing we need I guess.
I will open a PR and take a look at the existing tests.

**Comment by scaytrase** [comment]
> There is no defaults sets for operation and path if I'm not mistaken.

Hm, yes, there are no inheritance for default values. Sounds promising!

**Comment by lezhnev74** [comment]
I took a glance over `PathFinderTest`. I think it lacks a test for "servers inheritance". This package will benefit greatly from extra test.

**Comment by elythyr** [comment]
I added some test cases in `FromCommunity/Issue79Test.php`, during the review you'll just have to tell me if you want other cases to be tested and if you prefer the tests to be in `PathFinderTest` instead.
