### ISSUE TITLE
Show which attribute is referenced in KeywordMismatch exception

### ISSUE THREAD

**Issue by smujaddid** [thephpleague/openapi-psr7-validator#84]
### Information
Package version: 0.12.1
PHP 7.4

### Test case:
Consider the following attribute object:
```apib
+ Attributes (object)
    + username (string, required)
    + type (string, required)
```
With a response body, for example:
```json
{
  "username": "whoami",
  "type": null
}
```
Currently when validating using above will throwing the following exceptios
```php
League\OpenAPIValidation\PSR7\Exception\Validation\InvalidBody::class
League\OpenAPIValidation\Schema\Exception\KeywordMismatch::class
```
this will only show the following exception message:

```php
"Keyword validation failed: Value cannot be null"
```

It is not clear which attribute caused this based on the message.
I found that there is no way to get the attribute name from the exception (or previous exception),
because the `BreadCrumb` class doesn't expose `$compoundIndex` which in my case holds the attribute name.

### Suggestion
I suggest to expose `$compountIndex` value with a getter method within BreadCrumb class.

**Comment by lezhnev74** [comment]
I wonder, can you get these chain of keys from `BreadCrumb::buildChain() : array`? 
https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/Schema/BreadCrumb.php#L51

**Comment by smujaddid** [comment]
Wow, my bad! I never thought of that.
Thank you for pointing the way.

It is solved then :)

**Comment by lezhnev74** [comment]
I liked how well described the above issue was. Thumb up for that.
