### ISSUE TITLE
Support validation using separate OpenAPI files

### ISSUE THREAD

**Issue by thunderer** [thephpleague/openapi-psr7-validator#85]
Hi, I have an OpenAPI description split to several top-level files (ie. `openapi`, `info`, `paths`, etc.) for each application module. Each file then imports `paths` (per resource) and `schemas` from other files in subdirectories. These files also contain top-level OpenAPI structure but are used only as JSON files to be imported elsewhere. Since the complete description contains tens of thousands of lines it is not feasible to merge them back. We validate request and response contract while running E2E scenarios so matching each file to a certain path is also not a viable solution.

From what I see `ValidatorBuilder` can be created using a single file only. Are there any plans on adding support for multiple OpenAPI files? In my case, these files do not overlap, but validating duplicate schemas names and paths would be an added benefit. Is there any other viable approach for that issue given the current state of this library? Thanks in advance for your reply.

**Comment by scaytrase** [comment]
I think the proper way is to somehow utilize the `$ref`s, but I dunno if it's relevant for top level objects. In any case for building the schema responsible code is here https://github.com/cebe/php-openapi/blob/master/src/Reader.php

**Comment by thunderer** [comment]
I see that this issue can be somewhat circumvented through manual reading and merging these top-level files:

```php
$loadFile = fn(string $path) => json_decode(file_get_contents($path), true, JSON_THROW_ON_ERROR);
$schema = Reader::readFromJson(json_encode(array_merge_recursive(
    $loadFile(__DIR__.'/openapi/module1.json'),
    $loadFile(__DIR__.'/openapi/module2.json'),
    $loadFile(__DIR__.'/openapi/module3.json'),
    // ... more ...
)));
// that slash suffix is required for proper $ref resolution
$schema->resolveReferences(new ReferenceContext($schema, __DIR__.'/openapi/'));

$request = new RequestValidator($schema);
$response = new ResponseValidator($schema);
```

**Comment by thunderer** [comment]
@scaytrase I'm not aware of any way of merging top-level OpenAPI descriptions through `$ref`s. Even in my current approach we reference paths from other files through:

```
"/users": { "$ref": "resources/user.json#/paths/~1collection" }
```

**Comment by scaytrase** [comment]
Yea, but resolving `$ref`erences is already supported. That's the point

**Comment by thunderer** [comment]
@scaytrase that works only for a single top-level OpenAPI description that references all paths. What I'm looking for is an ability to specify multiple top-level files (with separate paths) without relying on manual call to `array_merge_recursive()` which isn't really a solution. So far I can confirm that it didn't throw an exception, but I still need to verify if it actually validates everything like it should. :)

As far as I understand, I can't create a single top-level file which would then import paths with `allOf` and `$ref`s. Is adding support for multiple files something you consider within scope of this library?

**Comment by scaytrase** [comment]
Yea, there is a paragraph about it in spec https://swagger.io/docs/specification/using-ref/#allowed-places It can't be done like I wanted

> Is adding support for multiple files something you consider within scope of this library?

I hope the better place to implement it is @cebe library mentioned above. But also I think It's a kind of a custom solution. For exapmle if you will spread your files not only into files, but also into directories (i.e module1/paths.json, module1/refs.json, module2/paths.json, module2/refs.json). After this moment it's impossible to correctly work with references, since all files are resolved at the moment of schema parsing against single root (the virtual "root" schema which may even not exist at all)
