### ISSUE TITLE
Example use cases of when validating requests is useful?

### ISSUE THREAD

**Issue by osteel** [thephpleague/openapi-psr7-validator#86]
Hi,

This might sound a bit weird, but I can't really think of a reason why I'd want to validate a request.

Validating responses makes a lot of sense to me – you've got an API, an OpenAPI definition describing it, and you want to make sure your API endpoints return responses which conform to the OpenAPI definition.

But the requests?

I might be missing something really obvious here, but hopefully you know of some example use cases that will make it click for me.

Cheers,

Yannick

**Comment by lezhnev74** [comment]
Hey @osteel! In client-server model, request messages are forged by clients, response messages by servers. Specs are common ground which imposes rules on both.

> you've got an API, an OpenAPI definition describing it

This is a common usecase, however just one of a many. In general, specs can come from a third party, that controls the protocol. Clients and server can be implemented by different parties as well. Messages validation can happen somewhere in the middle of the network between servers and clients (on some proxy server).

**Comment by sunkan** [comment]
Hey @osteel 

I use it to validate that the input is conforming to the specification witch in turns makes creation of the Input object simpler.

And by having the validation happen in a middleware we can return early and not wast resource on invalid requests. 

I usually turn of the response validation when the api goes into production because the response your in control.

**Comment by osteel** [comment]
@lezhnev74 @sunkan thanks for your replies. I think I'm just biased because I'm a backend developer and couldn't think beyond my own use cases as an API maintainer, but your examples make sense.

Closing this now, but if anyone wants to add some more examples, please do!
