### ISSUE TITLE
Valid URIs are rejected if they are not a URL

### ISSUE THREAD

**Issue by garethellis36** [thephpleague/openapi-psr7-validator#89]
The class `StringURI` uses `filter_var($value, FILTER_VALIDATE_URL) !== false` to validate properties of type `string` and format `uri`. This means that a value which is a valid URI but not a URL (e.g. `auth:invalid`) fails validation.

I think the `StringURI` could be updated to use the `league/uri` package instead. Would you be open to a PR for this?

**Comment by scaytrase** [comment]
Sure, at least I'd like to see PR with some failing tests in order to better understand the problem
